- hosts: webserver
  tasks:
    - name: installing git
      apt: name=git state=latest
      when: ansible_os_family == "Redhat"

    - name: installing maven
      apt: name=maven state=latest
      when: ansible_os_family == "Debian"

