- hosts: webserver
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
      notify: start apache2
    - name: install lynx
      apt: name=lynx state=latest  
      notify: start lynx
  handlers:
    - name: start apache2
      service: name=apache2 state=started
    - name: start lynx
      service: name=lynx state=started


