- hosts: webserver
  tasks:
    - name:  installing apache2 
      apt: name=apache2 state=present
      notify: start apache2
  handlers:
    - name: start apache2
      service: name=apache2 state=started      
